server:
  port: 8080
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8666/eureka/
    register-with-eureka: true
logbook:
  write:
    level: info
  format:
    style: curl
  config: classpath:log4j2.xml


