server:
  port: 8777
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: mars-work.local
  server:
    renewal-percent-threshold: 0.5  #留存的服务实例低于多少比例进入保护模式
    enable-self-preservation: true  #是否开始保护模式

  client:
    register-with-eureka: true  #是否注册eureka
    fetch-registry: true         #是否启用获取服务注册信息
    serviceUrl:
      defaultZone: http://mars-work.local:8666/eureka/


